name: dev environment workflow

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build
        run: |
          python setup.py build

  output:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Result
        run: |
           echo "Triggered by: ${{ github.actor }}"
           echo "build on ubuntu-latest Job status: ${{ needs.build.outputs['ubuntu-latest'].result }}"
           echo "build on windows-latest Job status: ${{ needs.build.outputs['windows-latest'].result }}"
